### ISSUE TITLE
insta リール活用

### ISSUE THREAD

**Issue by MiharuIwao10** [LinQTeam/whoo-community#6]

**Comment by ammiikaa** [comment]
## Target

- 既存ユーザー

## Objective

- ユーザーとの交流
- whoo自体に楽しいという印象付け
- whooのコアファンの創出

## How

- リポスト
    - #whooなんとかをつけてもらう、「タグる」
    - user generated contents
        - インフルエンサー・芸能人などによる分かりやすい商用広告よりも、一般ユーザーによるUGCが評価・信頼され、他のユーザーの購買・来店行動に影響
            
            **UGCが発生しやすい環境づくりや、積極的な情報発信を促すユーザーへの働きかけが必要**
            専用のハッシュタグを準備し、ユーザーがハッシュタグをつけて投稿したらプレゼントするというハッシュタグキャンペーンを実施。
            
- ユーザーと気軽に話せるようなplatoform化
    - whooの紹介に固執する必要はない。whooのインスタの垢のファンを作る
        - 質問箱で、今年の仮装は何するの？など投稿して、またストーリーで共有
        - みんなの初デート場所はどこ？
        - みんなはどっち派？スプラ参照
- ポジティブな発信だけでなく、ネガティブな情報も隠さず公開することで真摯な態度が評価される。ユーザーから発信されたものに対して、いち早くタイミングで否定。
